const gamesTypes = {
  UPDATE_AVAILABLE_GAMES: 'UPDATE_AVAILABLE_GAMES',
  UPDATE_CURRENT_GAME: 'UPDATE_CURRENT_GAME',
  ADD_PLAYER: 'ADD_PLAYER',
  UPDATE_CURRENT_GAME_LOBBY_STATE: 'UPDATE_CURRENT_GAME_LOBBY_STATE'
};

export default gamesTypes;
