const gamesTypes = {
  UPDATE_AVAILABLE_GAMES: 'UPDATE_AVAILABLE_GAMES',
  UPDATE_CURRENT_GAME: 'UPDATE_CURRENT_GAME',
  CLEAR_CURRENT_GAME: 'CLEAR_CURRENT_GAME',
  SET_CURRENT_GAME_HOST: 'SET_CURRENT_GAME_HOST',
  ADD_PLAYER: 'ADD_PLAYER',
  REMOVE_PLAYER: 'REMOVE_PLAYER',
  UPDATE_CURRENT_GAME_LOBBY_STATE: 'UPDATE_CURRENT_GAME_LOBBY_STATE',
  UPDATE_CURRENT_GAME_PLAYERS: 'UPDATE_CURRENT_GAME_PLAYERS',
  UPDATE_CURRENT_GAME_CURRENT_CARD: 'UPDATE_CURRENT_GAME_CURRENT_CARD',
  REMOVE_PLAYER_CARD: 'REMOVE_PLAYER_CARD',
  ADD_PLAYER_CARD: 'ADD_PLAYER_CARD'
};

export default gamesTypes;
