const playerTypes = {
  SET_PLAYER_NAME: 'SET_PLAYER_NAME',
  SET_PLAYER_NAME_PENDING: 'SET_PLAYER_NAME_PENDING',
  SET_PLAYER_NAME_ERROR: 'SET_PLAYER_NAME_ERROR',
  SET_PLAYER_NAME_SUCCESS: 'SET_PLAYER_NAME_SUCCESS'
};

export default playerTypes;
